[build]
  publish = "dist"
  command = "npm run build"

[context."staging"]
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"

